language: objective-c
osx_image: xcode6.4

before_script:
  - export LANG=en_US.UTF-8
before_install:
  - gem update cocoapods
script:
  - cd ./Testing/Xcode-desktop
  - pod install
  - xctool -workspace YapDatabase.xcworkspace -scheme YapDatabase -sdk macosx -arch x86_64 test
